{% set name = "cryptopp" %}
{% set version = "7.0.0" %}
{% set sha256 = "3ee97903882b5f58c88b6f9d2ce50fd1000be95479180c7b4681cd3f4c1c7629" %}

package:
  name: {{ name| lower }}
  version: {{ version }}

source:
  fn: {{ name | upper }}-{{ version | replace('.', '_') }}.tar.gz
  url: https://github.com/weidai11/cryptopp/archive/{{ name | upper }}_{{ version | replace('.', '_') }}.tar.gz
  sha256: {{ sha256 }}

  patches:
    # Replaces flag -march=native with flag  -mtune=generic
    # This flag can be removed via cmake optino in the next release
    - 0001-cmake-mtune-fix.patch  # [not win]

build:
  number: 0
  skip: true  # [win and py27]
  features:
    - vc9     # [win and py27]
    - vc10    # [win and py34]
    - vc14    # [win and py>=35]

requirements:
  build:
    - toolchain
    - cmake
    - python  # [win]
    - vc 9    # [win and py27]
    - vc 10   # [win and py34]
    - vc 14   # [win and py>=35]

  run:
    - vc 9    # [win and py27]
    - vc 10   # [win and py34]
    - vc 14   # [win and py>=35]

test:
  commands:
    - test -f ${PREFIX}/lib/libcryptopp.a    # [unix]
    - test -d ${PREFIX}/include/cryptopp     # [unix]
    - test -f ${PREFIX}/lib/cmake/cryptopp/cryptopp-config.cmake          # [unix]
    - test -f ${PREFIX}/lib/cmake/cryptopp/cryptopp-config-version.cmake  # [unix]
    - if exist %LIBRARY_LIB%\cryptopp-static.lib (exit 0) else (exit 1)       # [win]
    - if exist %LIBRARY_LIB%\cmake\cryptopp\cryptopp-config.cmake (exit 0) else (exit 1)          # [win]
    - if exist %LIBRARY_LIB%\cmake\cryptopp\cryptopp-config-version.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://www.cryptopp.com
  license: Boost-1.0
  license_file: License.txt
  summary: A C++ Class Library of Cryptographic Schemes

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
