{% set name = "cryptopp" %}
{% set version = "8.6.0" %}
{% set sha256 = "9304625f4767a13e0a5f26d0f019d78cf9375604a33e5391c3bf2e81399dfeb8" %}
{% set sha256_cmake = "970b20d55dbf9d6335485e72c9f8967d878bf64bbd3de6aa28436beb6799c493" %}

package:
  name: {{ name| lower }}
  version: {{ version }}

source:
  - fn: {{ name | upper }}-{{ version | replace('.', '_') }}.tar.gz
    url: https://github.com/weidai11/cryptopp/archive/{{ name | upper }}_{{ version | replace('.', '_') }}.tar.gz
    sha256: {{ sha256 }}
  - folder: cryptopp-cmake
    fn: cmake-{{ name | upper }}-{{ version | replace('.', '_') }}.tar.gz
    url: https://github.com/noloader/cryptopp-cmake/archive/{{ name | upper }}_{{ version | replace('.', '_') }}.tar.gz
    sha256: {{ sha256_cmake }}

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, exact=True) }}

requirements:
  build:
    - cmake <3.12
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - test -f ${PREFIX}/lib/libcryptopp.a      # [unix]
    - test -f ${PREFIX}/lib/libcryptopp.so     # [linux]
    - test -f ${PREFIX}/lib/libcryptopp.dylib  # [osx]
    - test -d ${PREFIX}/include/cryptopp       # [unix]
    - test -f ${PREFIX}/lib/cmake/cryptopp/cryptopp-config.cmake          # [unix]
    - test -f ${PREFIX}/lib/cmake/cryptopp/cryptopp-config-version.cmake  # [unix]
    - if exist %LIBRARY_LIB%\cryptopp-static.lib (exit 0) else (exit 1)   # [win]
    - if exist %LIBRARY_LIB%\cmake\cryptopp\cryptopp-config.cmake (exit 0) else (exit 1)          # [win]
    - if exist %LIBRARY_LIB%\cmake\cryptopp\cryptopp-config-version.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://www.cryptopp.com
  license: BSL-1.0
  license_file: License.txt
  summary: A C++ Class Library of Cryptographic Schemes

extra:
  recipe-maintainers:
    - apmorton
    - SylvainCorlay
    - JohanMabille
