{% set name = "cryptopp" %}
{% set version = "8.3.0" %}
{% set sha256 = "63304c6f943f435a4e385273e15abb69cff3b85a44663150bf5a6069b84abd43" %}

package:
  name: {{ name| lower }}
  version: {{ version }}

source:
  fn: {{ name | upper }}-{{ version | replace('.', '_') }}.tar.gz
  url: https://github.com/weidai11/cryptopp/archive/{{ name | upper }}_{{ version | replace('.', '_') }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_compatible(name, exact=True) }}

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

  run:

test:
  commands:
    - test -f ${PREFIX}/lib/libcryptopp.a      # [unix]
    - test -f ${PREFIX}/lib/libcryptopp.so     # [linux]
    - test -f ${PREFIX}/lib/libcryptopp.dylib  # [osx]
    - test -d ${PREFIX}/include/cryptopp       # [unix]
    - test -f ${PREFIX}/lib/cmake/cryptopp/cryptopp-config.cmake          # [unix]
    - test -f ${PREFIX}/lib/cmake/cryptopp/cryptopp-config-version.cmake  # [unix]
    - if exist %LIBRARY_LIB%\cryptopp-static.lib (exit 0) else (exit 1)   # [win]
    - if exist %LIBRARY_LIB%\cmake\cryptopp\cryptopp-config.cmake (exit 0) else (exit 1)          # [win]
    - if exist %LIBRARY_LIB%\cmake\cryptopp\cryptopp-config-version.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://www.cryptopp.com
  license: Boost-1.0
  license_file: License.txt
  summary: A C++ Class Library of Cryptographic Schemes

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
