appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: xkf0CyU+Per/DRSlY4gDTYukV270gBEYO8M8P/H07y4o1eRYIqneETI9qqNz8/tMNJTnZrjeNGIXu2gI1QyrVpOFEllqfcIYPxMdSKLcMfBNKIMDjIKCiU+LcFsRqBVyI37iKRpwbPyg6YS0imh0lpffj3gxfs2cI/gFb9jhB8xHe/vkskaBBb494qI741A4vgYMRz8iipl7tCwYmHqZs/+VelFo7zYxJLOM4+KxDYzx7xXvrtL+rK7QghwUcslK3SjZe/X2CKGzhXlW7xAV7X9/KFkhz5bd6LQKdzqVK3vAZfYmNBoC2nXmjm/m9cI/xW0EG/qFwew6dMawgVlTDy82EE6jKtha48Xzdee0vlByY6Gyk7K/oCgr8U1X/h3OhayrCs/2Lc1lkOUai00WjeF9/CwK9W1GdA3dSVtaJgv5QG1fx7j1MZLPesLLfg6g2szWW1ivhFfrnzJarTe6vXgUxuid8Z8YN2jLfsoBh7W9FdmZYVnaJEsKJvwkkqoR3Xy0DQSWkikk8c3PPef+fMzXVgQnGfoKO7KCqtyaEC7kuNRRCHZeChx8CWYkZMCE4N/v55/YhFcTy7wKMgOYYNdR9BbuW8HvYuPaG8uJRjXytEeM7t9zfM99qsZl10sKyDwSB63TuSaby51f+gGzFT9deu1SnIEhHEM7+lcd5gQ=}
provider: {linux_aarch64: default, linux_ppc64le: default}
conda_forge_output_validation: true
